/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Doubt {
  'question' : string,
  'studentName' : string,
  'subject' : string,
  'answer' : [] | [string],
  'classNum' : bigint,
}
export interface Lesson {
  'title' : string,
  'description' : string,
  'pdfUrl' : string,
  'notes' : string,
  'longVideoUrl' : string,
  'shortVideoUrl' : string,
  'videoUrl' : string,
}
export interface Poll {
  'question' : string,
  'subject' : string,
  'votes' : Array<bigint>,
  'options' : Array<string>,
  'classNum' : bigint,
}
export interface QuizQuestion {
  'question' : string,
  'correctIndex' : bigint,
  'options' : Array<string>,
}
export interface UserProfile { 'name' : string, 'classNum' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLesson' : ActorMethod<[bigint, string, Lesson], undefined>,
  'addPoll' : ActorMethod<
    [bigint, string, { 'question' : string, 'options' : Array<string> }],
    undefined
  >,
  'addQuizQuestion' : ActorMethod<[bigint, string, QuizQuestion], undefined>,
  'answerDoubt' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeLesson' : ActorMethod<[bigint, string, string], undefined>,
  'getAllDoubts' : ActorMethod<[], Array<Doubt>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedLessons' : ActorMethod<[], Array<[bigint, string, string]>>,
  'getDoubtsByClassSubject' : ActorMethod<[bigint, string], Array<Doubt>>,
  'getLessons' : ActorMethod<[bigint, string], Array<Lesson>>,
  'getPolls' : ActorMethod<[bigint, string], Array<Poll>>,
  'getQuizQuestions' : ActorMethod<[bigint, string], Array<QuizQuestion>>,
  'getQuizScores' : ActorMethod<[], Array<[bigint, string, bigint]>>,
  'getSubjects' : ActorMethod<[bigint], Array<string>>,
  'getUnansweredDoubts' : ActorMethod<[], Array<Doubt>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitDoubt' : ActorMethod<[string, bigint, string, string], undefined>,
  'submitQuizScore' : ActorMethod<[bigint, string, bigint], undefined>,
  'votePoll' : ActorMethod<[bigint, string, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];