/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lesson = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'pdfUrl' : IDL.Text,
  'notes' : IDL.Text,
  'longVideoUrl' : IDL.Text,
  'shortVideoUrl' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'question' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Doubt = IDL.Record({
  'question' : IDL.Text,
  'studentName' : IDL.Text,
  'subject' : IDL.Text,
  'answer' : IDL.Opt(IDL.Text),
  'classNum' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'classNum' : IDL.Nat,
});
export const Poll = IDL.Record({
  'question' : IDL.Text,
  'subject' : IDL.Text,
  'votes' : IDL.Vec(IDL.Nat),
  'options' : IDL.Vec(IDL.Text),
  'classNum' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLesson' : IDL.Func([IDL.Nat, IDL.Text, Lesson], [], []),
  'addPoll' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Record({ 'question' : IDL.Text, 'options' : IDL.Vec(IDL.Text) }),
      ],
      [],
      [],
    ),
  'addQuizQuestion' : IDL.Func([IDL.Nat, IDL.Text, QuizQuestion], [], []),
  'answerDoubt' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeLesson' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'getAllDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedLessons' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getDoubtsByClassSubject' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Doubt)],
      ['query'],
    ),
  'getLessons' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Vec(Lesson)], ['query']),
  'getPolls' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Vec(Poll)], ['query']),
  'getQuizQuestions' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(QuizQuestion)],
      ['query'],
    ),
  'getQuizScores' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getSubjects' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getUnansweredDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDoubt' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'submitQuizScore' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'votePoll' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lesson = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'pdfUrl' : IDL.Text,
    'notes' : IDL.Text,
    'longVideoUrl' : IDL.Text,
    'shortVideoUrl' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Doubt = IDL.Record({
    'question' : IDL.Text,
    'studentName' : IDL.Text,
    'subject' : IDL.Text,
    'answer' : IDL.Opt(IDL.Text),
    'classNum' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'classNum' : IDL.Nat });
  const Poll = IDL.Record({
    'question' : IDL.Text,
    'subject' : IDL.Text,
    'votes' : IDL.Vec(IDL.Nat),
    'options' : IDL.Vec(IDL.Text),
    'classNum' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLesson' : IDL.Func([IDL.Nat, IDL.Text, Lesson], [], []),
    'addPoll' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Record({ 'question' : IDL.Text, 'options' : IDL.Vec(IDL.Text) }),
        ],
        [],
        [],
      ),
    'addQuizQuestion' : IDL.Func([IDL.Nat, IDL.Text, QuizQuestion], [], []),
    'answerDoubt' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeLesson' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'getAllDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedLessons' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getDoubtsByClassSubject' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Doubt)],
        ['query'],
      ),
    'getLessons' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Vec(Lesson)], ['query']),
    'getPolls' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Vec(Poll)], ['query']),
    'getQuizQuestions' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(QuizQuestion)],
        ['query'],
      ),
    'getQuizScores' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getSubjects' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
    'getUnansweredDoubts' : IDL.Func([], [IDL.Vec(Doubt)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDoubt' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'submitQuizScore' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'votePoll' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };