/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Doubt {
    question: string;
    studentName: string;
    subject: string;
    answer?: string;
    classNum: bigint;
}
export interface Lesson {
    title: string;
    description: string;
    notes: string;
    videoUrl: string;
}
export interface QuizQuestion {
    question: string;
    correctIndex: bigint;
    options: Array<string>;
}
export interface backendInterface {
    addLesson(classNum: bigint, subject: string, lesson: Lesson): Promise<void>;
    addQuizQuestion(classNum: bigint, subject: string, question: QuizQuestion): Promise<void>;
    answerDoubt(index: bigint, answer: string): Promise<void>;
    completeLesson(classNum: bigint, subject: string, lessonTitle: string): Promise<void>;
    getAllDoubts(): Promise<Array<Doubt>>;
    getCompletedLessons(): Promise<Array<[bigint, string, string]>>;
    getDoubtsByClassSubject(classNum: bigint, subject: string): Promise<Array<Doubt>>;
    getLessons(classNum: bigint, subject: string): Promise<Array<Lesson>>;
    getQuizQuestions(classNum: bigint, subject: string): Promise<Array<QuizQuestion>>;
    getQuizScores(): Promise<Array<[bigint, string, bigint]>>;
    getSubjects(classNum: bigint): Promise<Array<string>>;
    getUnansweredDoubts(): Promise<Array<Doubt>>;
    submitDoubt(studentName: string, classNum: bigint, subject: string, question: string): Promise<void>;
    submitQuizScore(classNum: bigint, subject: string, score: bigint): Promise<void>;
}
import type { Doubt as _Doubt } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addLesson(arg0: bigint, arg1: string, arg2: Lesson): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLesson(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLesson(arg0, arg1, arg2);
            return result;
        }
    }
    async addQuizQuestion(arg0: bigint, arg1: string, arg2: QuizQuestion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuizQuestion(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuizQuestion(arg0, arg1, arg2);
            return result;
        }
    }
    async answerDoubt(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.answerDoubt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.answerDoubt(arg0, arg1);
            return result;
        }
    }
    async completeLesson(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeLesson(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeLesson(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllDoubts(): Promise<Array<Doubt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoubts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoubts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedLessons(): Promise<Array<[bigint, string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedLessons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedLessons();
            return result;
        }
    }
    async getDoubtsByClassSubject(arg0: bigint, arg1: string): Promise<Array<Doubt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoubtsByClassSubject(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoubtsByClassSubject(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessons(arg0: bigint, arg1: string): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessons(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessons(arg0, arg1);
            return result;
        }
    }
    async getQuizQuestions(arg0: bigint, arg1: string): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestions(arg0, arg1);
            return result;
        }
    }
    async getQuizScores(): Promise<Array<[bigint, string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizScores();
            return result;
        }
    }
    async getSubjects(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjects(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjects(arg0);
            return result;
        }
    }
    async getUnansweredDoubts(): Promise<Array<Doubt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnansweredDoubts();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnansweredDoubts();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitDoubt(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDoubt(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDoubt(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitQuizScore(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizScore(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizScore(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Doubt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Doubt): Doubt {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    question: string;
    studentName: string;
    subject: string;
    answer: [] | [string];
    classNum: bigint;
}): {
    question: string;
    studentName: string;
    subject: string;
    answer?: string;
    classNum: bigint;
} {
    return {
        question: value.question,
        studentName: value.studentName,
        subject: value.subject,
        answer: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.answer)),
        classNum: value.classNum
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Doubt>): Array<Doubt> {
    return value.map((x)=>from_candid_Doubt_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
